### ISSUE TITLE
PMC-780 Urethane for M2 - dry or wet? 

### ISSUE THREAD

**Issue by dylanvaughn** [grablab/openhand-hardware#1]
Hello - in the M2 BOM it says PMC-780 Urethane - on the provided link:

http://www.smooth-on.com/index.php?cPath=1148

there are two options - wet or dry - which should be purchased?

Thanks, Dylan

**Comment by jessewalton** [comment]
You want DRY. The wet is used for molding concrete.

**Comment by dylanvaughn** [comment]
OK that's what I thought just wanted to be sure - thanks!

**Comment by grablab** [comment]
Just to confirm, dry! I'll update the documentation for clarification. Thanks!

**Comment by jbohren** [comment]
> Just to confirm, dry! I'll update the documentation for clarification. Thanks!

Are docs in source control too somewhere, or are they only on the project website?

**Comment by grablab** [comment]
Project website. I can add them to the source control too.

**Comment by jbohren** [comment]
> Project website. I can add them to the source control too.

If they're in tex or something that would be really cool, and make it easy to contribute fixes like this.
